# The version control workflow

:caution: Under development :caution:

Today's topics are:

1. Exploring data frames (in Rmd!)
2. Working locally with git

To participate in today's class, you'll need:

- [git installed](http://happygitwithr.com/install-git.html)
- A GitHub account
- RStudio installed
- Access to the command line (can do through RStudio)

## Exploring data frames (in Rmd!)

## Learning Objectives

- Describe the difference between git and GitHub, and name similar software
- Merge repository branches via pull requests on GitHub, resolving merge conflicts if necessary

In our R exploration last time, we saw one way to bundle together multiple pieces of information: _vectors_. Now, we'll turn to _data frames_.

By the end of this lesson, students are expected to be able to:

- Describe common properties of "built-in" R data frames using R
- Extract columns from a data frame

## Resources

This lesson closely mirrors the [stat545.com: care-feeding-data](http://stat545.com/block006_care-feeding-data.html) page for exploring data frames.

## Getting Started

We'll be working with the gapminder data set. To access it, in any R console, run the following:

```
install.packages('gapminder')
```

## Demonstration

FIRST, let's ensure your [participation repo](http://stat545.com/Classroom/participation.html) is setup.

1. Go to your github.com profile.
2. If you have a participation repository, but it's not called `STAT545_participation`, I'll show you how to rename it. 
3. If you DON'T have a participation repository set up, let's do that (I'll make one, too).

Now, I've started a "cleaned up" version of the Rmd file we were exploring last time. Find it [on GitHub](https://github.com/STAT545-UBC/Classroom/blob/master/notes/cm004-exercise-df.Rmd)!

Let's build this up, and submit the result to your [participation repository](http://stat545.com/Classroom/participation.html) for your participation assessment. 

## Working locally with git

## Learning Objectives

The concepts we'll be touching on here are:

- clone
- stage
- commit (again!)
- pull/push

By the end of the lesson, students are expected to be able to:

- Demonstrate the above concepts using RStudio's git client with your participation GitHub repository.

## Resources

Want to try a similar lesson to today's, but on your own? Follow along with [happygitwithr: rstudio-git-github](http://happygitwithr.com/rstudio-git-github.html), which is closely aligned with the goals of this lesson.

Want to learn more, above and beyond what's done in class? Take a look at these:

- Excellent [resource by GitHub](https://blog.github.com/2015-06-08-how-to-undo-almost-anything-with-git/) on how to "undo" almost anything (including "going back" to a previous state).

## Getting Started

You'll need to [config your git](http://happygitwithr.com/hello-git.html) using the command line.

Your RStudio will probably be able to "find" git. But if it can't, you'll encounter errors. See [happygitwithr: see-git](http://happygitwithr.com/rstudio-see-git.html) for help. 

__Optional__ (but recommended): After class, you might want to [cache](http://happygitwithr.com/credential-caching.html) your credentials so that you don't have to keep inserting your password.

## Demonstration

The end product of this demonstration is a locally modified version of our data frame exploration, pushed to GitHub.

- What are "git clients"? 
    - We'll be using the git client built-in to RStudio.
- Cloning: 
    1. Concept (remember "branches"?)
    2. Practice with your participation repo. I'll be using the [Classroom](https://github.com/STAT545-UBC/Classroom) repo. 
        - In RStudio, File -> New Project -> Version Control -> Git.
        - You should see a `Git` tab in RStudio, upper-right corner window. If not, see [happygitwithr: see-git](http://happygitwithr.com/rstudio-see-git.html) for help.
    3. Take a look at the files you just downloaded!
- By the way:   
    - What's an RStudio "project"?
    - We don't need to edit a file _with RStudio_ to use its git client!
    - File doesn't need to have anything to do with R, either.
- Staging and committing:
    1. Concept
    2. Modify your Rmd exploration from earlier (just add a new line).
    3. Stage and commit
- Push/Pull:
    1. Concept
    2. Try pushing!

## Adopting git in your workflow

__Before the world of git:__

_Save_ perpetually.

__After embracing git:__

_Save_ perpetually, _commit_ often, _push_ [in case of fire](https://github.com/louim/in-case-of-fire/blob/master/in_case_of_fire.pdf).

__Need help?__

If you're encountering problems, try:

- As always, google search. 
- [Burn it all down](http://happygitwithr.com/burn.html).
    - There's even an [xkcd comic](https://xkcd.com/1597/) on this.

The git documentation is not friendly. There's even a [parody](https://git-man-page-generator.lokaltog.net/) on it.


## If there's time remaining

- Concepts related to [getting help](http://stat545.com/help-general.html) in R (or with other computational problems):
    - Google the error message (works most of the time)
    - Write a question using a MWE. You'll solve it yourself most of the time.
    - Post question to thread such as SO.
- "Lab"


### Live-Coding: Branching and Merging

The notion of _branching_ and _merging_ shows up seemingly everywhere in version control. You'll encounter _merge conflicts_, too.

To demonstrate concepts, let's look at a _repository branch_. There are other types of branches, as we'll see. For more info on this, see [the GitHub documentation](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/). 

NOTE: I'm deferring the motivation for repo branching until later. 

1. Create a new branch via the home page of your repo (find the "branch" button). Call it `test1`.
2. To the README on the `test1` branch, add a relative link to the other `.md` file in the repo (using markdown syntax).
3. Explore: 
    - switch between branches to see that the repo structure is different.
    - Diagram of commit history for both branches.
4. Merge the branch to "master".

Part 2: 

1. Make a new branch called `test2`.
2. Edit line 1 of the README _on both branches_ to something different in both cases.
3. Try merging. You'll get a _merge conflict_ -- go ahead and resolve it, then merge. 


#### Learning Objectives: Collaboration with GitHub

The primary focus here is learning about __leveraging GitHub's version control for collaboration__. The concepts are:

- GitHub Pages
- Forking
- Pull Request

Specifically, by the end of today's class, students are expected to:

- Be able to make a basic website out of your participation repository using GitHub Pages
- Know roughly what the above concepts are about

#### Demonstration

For participation marks, by the end of this demonstration: 

- you'll have a GitHub pages website set up for your participation repo
- you __don't need to have__ anything for the forking exercise!

Checklist:

1. Set up a basic "GitHub pages" website with your participation repo:
    1. Go to "settings" on your repo.
    2. Scroll down to "GitHub Pages"
    3. Under "Source", click the "None" drop-down button, and select the branch you want to turn into a website.
2. Forking a repo: 
    1. Let's try forking the `Classroom` repo.
    2. We'll make a change, and will submit a pull request.

## Tagging a Release


#### Resources

The GitHub documentation is perhaps the best place to learn about these outside of class:

- [GitHub Pages](https://pages.github.com/)
- [Forking](https://help.github.com/articles/fork-a-repo/)
    - [happygitwithr: fork](http://happygitwithr.com/fork.html) is also a good resource.
- [Pull Request](https://help.github.com/articles/about-pull-requests/)
