# Advanced R

__WARNING: content subject to change__

## Review, and Looking Ahead

We're done with the "core concepts" of data wrangling and data vis, both of which are fundamental to exploratory data analysis (EDA). 

Now, we're starting more "specialized" topics for EDA, which will continue into STAT 547M.

## Today's Lessons

New for 2019:

here::here(); readxl? googlesheets? Maybe even list-columns and the `rsample` package. Maybe bookdown, or blogdown.

Old (perhaps deprecated, since lightly covered in cm002):

- "Flavours" of R objects
- Vectors, vectorization, and recycling.
- Lists

If time remains:

- Environments and Scoping

## Resources

Part I:

- Jenny's [Basic R Objects](http://stat545.com/block004_basic-r-objects.html) tutorial covers Part I. 
- A more thorough treatment of the topic can be found in [adv-r: Data Structures](http://adv-r.had.co.nz/Data-structures.html) and [adv-r: Subsetting](http://adv-r.had.co.nz/Subsetting.html).

Part II:

- [adv-r: Functions: Lexical Scoping section](http://adv-r.had.co.nz/Functions.html#lexical-scoping) 
- [adv-r: Environments](http://adv-r.had.co.nz/Environments.html): "Environment Basics" section, and "Function Environments" section (but don't worry about "binding environments" and "calling environments").


## Participation

Fill out the cm011-exercise.Rmd file, and push it to your participation repo. Links: [Rmd](https://github.com/STAT545-UBC/Classroom/blob/master/notes/cm011-exercise.Rmd), or [from html](http://stat545.com/Classroom/notes/cm011-exercise.nb.html).