---
title: "Assignments and Peer Review"
output: html_document
---

Assignments will be posted here as they are made available. 

## Schedule

Here are the deadlines for assignments and peer reviews, with links (to appear after assignments are released). All submissions are due by 11:59pm.

### STAT 545

| Assignment  | Assignment Due Date | Peer Review Due Date |
|-------------|---------------------|----------------------|
| [Homework 01](hw01/hw01.html) | September 18, 2018  | September 24, 2018 ([link](hw01/pr01.html)) |
| [Homework 02](hw02/hw02.html) | September 25, 2018  | October 01, 2018 |
| Homework 03 | October 02,   2018  | October 08, 2018 |
| Homework 04 | October 09,   2018  | October 15, 2018 |
| Homework 05 | October 19,   2018  | October 24, 2018 |

### STAT 547

| Link |  Homework Due Date  |  Peer Review Due Date | Topic |
| :--: | :---------------: | :-----------------: | :----: |
| Homework 06 | November 09, 2018 | November 12, 2018 | Choose your adventure! |
| Homework 07 | November 13, 2018 | November 16, 2018 | Automate a data analysis pipeline |
| Homework 08 | November 20, 2018 | November 23, 2018 | Build a Shiny app |
| Homework 09 | November 27, 2018 | December 05, 2018 | Write an R package |
| Homework 10 | December 06, 2018 | December 12, 2018 | Get data from the web |

## Logistics

Here is the general flow that will happen for the assignments and peer reviews. 

1. When an assignment is released, I will post a GitHub Issue in [Discussion-Internal](https://github.com/STAT545-UBC/Discussion-Internal), tagging the teaching team and students (you should get an email notification, too, unless you've somehow disabled this, are not `Watch`ing the Discussion-Internal repo, or did not inform me of your GitHub username).
2. You will be prompted to create a repository through GitHub Classroom, develop your homework responses on this repository, contained in the [STAT545-UBC-students](https://github.com/STAT545-UBC-students) Organization.
3. It would be useful for you to submit a link to your URL in canvas. We will be putting your grades there. 
4. You will be notified of two classmates to provide a peer review. Check out their submission, then write your feedback as an Issue in their repository before the deadline.
    - There is no need to tag the teaching team!

## Assignments

Components of each assignment will be graded on a 3-point scale. Here is the general rubric (*also consult any specific guidance given in the relevant assignment itself*).

Topic| Excellent: 3 | Satisfactory: 2 | Needs work: 1 |
|----| ------ |-------| -----|
|Coding style| Student has gone beyond what was expected and required, coding manual is followed, code is well commented | Coding style lacks refinement and has some errors, but code is readable and has some comments | Many errors in coding style, little attention paid to making the code human readable|
|Coding strategy| Complicated problem broken down into sub-problems that are individually much simpler. Code is efficient, correct, and minimal. Code uses appropriate data structure (list, data frame, vector/matrix/array). Code checks for common errors  | Code is correct, but could be edited down to leaner code. Some "hacking" instead of using suitable data structure. Some checks for errors. |   Code tackles complicated problem in one big chunk. Code is repetitive and could easily be functionalized. No anticipation of errors. |
|Presentation: graphs | Graph(s) carefully tuned for desired purpose. One graph illustrates one point | Graph(s) well chosen, but with a few minor problems: inappropriate aspect ratios, poor labels. | Graph(s) poorly chosen to support questions. |
|Presentation: tables | Table(s) carefully constructed to make it easy to perform important comparisons. Careful styling highlights important features. | Table(s) generally appropriate but possibly some minor formatting deficiencies.| Table(s) with too many, or inconsistent, decimal places. Table(s) not appropriate for questions and findings. Major display problems.|
|Achievement, mastery, cleverness, creativity|Student has gone beyond what was expected and required, e.g., extraordinary effort, additional tools not addressed by this course, unusually sophisticated application of tools from course.|Tools and techniques from the course are applied very competently and, perhaps,somewhat creatively. Chosen task was acceptable, but fairly conservative in ambition.|Student does not display the expected level of mastery of the tools and techniques in this course. Chosen task was too limited in scope.|
|Ease of access for instructor, compliance with course conventions for submitted work|Access as easy as possible, code runs! | Satisfactory | Not an earnest effort to reduce friction and comply with conventions  and/or code does not run|



The grade mapping is as follows:

| Grade | Percentage |
|-------|------------|
| 0 | 0% | 
| 1 | 50% | 
| 2 | 80% | 
| 3 | 100% |

Intermediate points are allowed, and follow a linear scale in between each point, so that the full mapping is depicted in the following chart:

```{r, echo=FALSE, fig.width=5, fig.height=3, fig.align='center'}
library(ggplot2)
qplot(c(0,1,2,3), c(0, 50, 80, 100), geom=c("point", "line")) +
    theme_bw() +
    scale_y_continuous("Percent grade", limits=c(0,100), breaks=0:5*20) +
    xlab("Integer grade")
```


## Peer Review

As part of this course you will be reviewing, commenting on, and marking other students' assignments. This is a mandatory part of the course and you will be marked on your peer reviews (15% of overall course mark).

### How to give a good peer review: 

* Give thoughtful, constructive and considerate comments. 
* Be specific and concise.
* Use the assignment rubric (above) for ideas about criteria to evaluate and comment on -- we've given you a template to work with [here](https://github.com/STAT545-UBC/Classroom/blob/master/assignments/peer-review-template.md).
* Try to learn something new and, if you succeed, point that out.
* If you can't find anything to praise or that you found helpful, then at least offer some suggestions in a kind way.

### How you will be marked: 

* It's binary. Each peer review will be deemed "good" or "needs more". This means you either get 0 or 100% on each peer review. 

* Hallmarks of "needs more" feedback:
	- Your review is so generic that it's hard to determine which assignment you're reviewing.
    - Your review is mean.
    - You can't find anything to praise/learn and yet you don't offer any suggestions either.

* Each review you do will get you 1 point if "good" and 0 points if "needs more". Those will be totalled over all assignments to form your peer review mark.

### How to submit a peer review:



### Additional resources:

Peer reviewing and critiquing others' work is a useful skill to develop during your graduate studies. Although these links deal mainly with the peer review of academic papers, most of the key points are applicable to our peer review process.

* [Reviewing academic papers by Jeff Leek](https://github.com/jtleek/reviews/blob/master/README.md)

* [Edicts for peer reviewing (Ebb & Flow blog)](http://evol-eco.blogspot.ca/2014/09/edicts-for-peer-reviewing.html)

* [Faculty of 1000 Research: tips for peer reviewing](http://f1000research.com/peer-reviewing-tips)

* [The section entitled "How to perform the actual code review"](http://zonca.github.io/2014/08/code-review-for-scientific-computing.html)

