---
title: "STAT 545 Class Meeting 04: The version control workflow"
output:
    html_notebook:
        toc: true
        theme: cerulean
        number_sections: true
editor_options: 
  chunk_output_type: inline
---

Today's topics are:

1. Exploring data frames (in Rmd!)
    - (originally from cm003)
2. Working locally with git
3. Collaboration with GitHub
    - (originally from cm002)

# Exploring data frames (in Rmd!)

## Learning Objectives

In our R exploration last time, we saw one way to bundle together multiple pieces of information: _vectors_. Now, we'll turn to _data frames_.

By the end of this lesson, students are expected to be able to:

- Describe common properties of "built-in" R data frames
- Extract columns (observations on a variable) from a data frame

## Resources

This lesson closely mirrors the [stat545.com: care-feeding-data](http://stat545.com/block006_care-feeding-data.html) page for exploring data frames.

## Getting Started

We'll be working with the gapminder data set. To access it, in any R console, run the following:

```
install.packages('gapminder')
```

## Demonstration

I've started a "cleaned up" version of the Rmd file we were exploring last time. Find it [on GitHub](https://github.com/STAT545-UBC/Classroom/blob/master/notes/cm004-exercise-df.Rmd)!

Let's build this up. Submit the result to your [participation repository](http://stat545.com/Classroom/participation.html) for your participation assessment. 

# Working locally with git

## Learning Objectives

- Demonstrate usage of RStudio's git client

## Resources

- Excellent [resource by GitHub](https://blog.github.com/2015-06-08-how-to-undo-almost-anything-with-git/) on how to "undo" almost anything

## Demonstration

GitHub can't offer the suite of editing capabilities that you have on your local machine. So we set up a _local_ version of the repo and communicate with the _remote_ repo. 

- Exercise: (Do together) Connect RStudio to git and GitHub
    - Did you `config` git? Enter the commands (with your credentials) specified at the top of [this](http://happygitwithr.com/hello-git.html#hello-git) page.
    - _Clone_ your github repo to your local machine in RStudio. [instructions](http://happygitwithr.com/rstudio-git-github.html#clone-the-new-github-repository-to-your-computer-via-rstudio)
        - Don't have the "Version Control" option after clicking File -> New Project? Follow [these](http://happygitwithr.com/rstudio-see-git.html) instructions.
    - Open your README file, and add a line. Could be `I added this line locally.`
    - Go over to the `git` tab. Stage, commit, pull, and push your change.
    - Navigate to your remote repo. Do you see the change? You should!

## Git take-home Lessons

- Working with git:
    - local repository: a self-contained project on your computer
    - remote repository: that project on some "cloud", like GitHub, BitBucket, your own server, ...
    - git client: program on your computer that helps you use git (commit, push, pull, ...)
- Adopt git in your workflow! This means:
    - Dedicate a self-contained directory to your project.
    - Set up an R project for the directory.
    - Set up git for that directory. 
    - __Save__ perpetually, __commit__ often, __pull/push__ (to github) periodically!
- git can be painful.
    - Problems? Often best to just burn it down and start fresh...
    - Documentation difficult to read. Check out [this parody](https://git-man-page-generator.lokaltog.net/) of github documentation. 
    - Use a git client to make it easier to work with git. RStudio, Source Tree, GitHub desktop, ...

# Collaboration with GitHub

## Learning Objectives: Collaboration with GitHub

The primary focus here is learning about __leveraging GitHub's version control for collaboration__. The concepts are:

- Collaborators
- Forking
- Pull Request
- Release
- GitHub Pages

Specifically, by the end of today's class, students are expected to be able to:

- Make a basic website out of their GitHub repository using GitHub Pages
- Tag a release of their GitHub repository 

## Resources

## Collaboration Concepts and Workflows

Let's look at the how and why of the following:

- Adding a collaborator
- Repo branching: why?
    - try new features
    - work separately
    - hold different content
- Private vs public repositories
    - Viewing is different from collaborating!
    - If you can, making your work public is a remarkably good thing: world of "open source".
- Forking as another type of branching
    - Learn more with [happygitwithr: fork](http://happygitwithr.com/fork.html)
- Tag a release of your repo
- Turn your repo into a website using GitHub pages

# If there's time remaining

- Know about useful resources online to get help with R, and technical tools in general.
- Design effective questions through minimum workable examples (MWE's).
