---
title: "STAT 545 Class Meeting 02: Getting Familiar with R"
output:
    html_notebook:
        toc: true
        theme: cerulean
        number_sections: true
editor_options: 
  chunk_output_type: inline
---

Today, we'll be looking at three things:

1. Basic exposure to the wonderful world of plain text
    - With a focus on authoring with markdown
2. Version control with GitHub
    - Fundamental concepts in version control through GitHub
3. Collaboration with GitHub
    - Workflows to optimize collaboration

To participate in today's lecture, you should have:

- A GitHub account
- RStudio installed

Reflections on the Shell from last time:

- Windows has its own language for the Shell. Thanks to those students contributing their Windows knowledge in [Discussion-Internal Issue #5](https://github.com/STAT545-UBC/Discussion-Internal/issues/5)!

# The Wonderful World of Plain Text

## Learning Objectives: Plain Text

By the end of today's class, students are expected to be able to:

- Name three key uses of plain text, and some types of plain text for each
- Author basic documents in ordinary markdown (easier than you think!) with RStudio
- Render a markdown document to html and pdf using RStudio
- Choose whether html or pdf is an appropriate output

## Orientation to Plain Text

Three uses of plain text relevant to data analytic work:

- authoring
- data storage
- scripts

Motivation for plain text:

- authoring: 
    - Delegating the formatting saves time and is distraction-free
    - Automate numbering
    - Automate changes to the formatting
    - Less error-prone (eg. matching font sizes)
    - ...
- data storage and scripts:
    - always machine readable

Types of plain text for each, with typical file extensions. STAT 545 focusses on those in __bold__:

- authoring
    - __markdown__ (`.md`) (and family!)
    - LaTeX (`.tex`)
    - You could say HTML, too...
- data storage
    - __csv/comma-separated values__ (`.csv`)
    - tsv/tab-separated values (`.tsv`)
    - JSON (`.json`)
    - XML (`.xml`) (although not its only use)
- scripts
    - __R__ (`.r`) -- _Next week_
    - python (`.py`)
    - javascript (`.js`)

Some noteworthy things:

- Rich text is different from syntax highlighting
- The _file viewer_ is independent from the _file_
    - Less so with proprietary software such as Word. 
- With plain text, the file extension doesn't really matter. 

## Markdown Crash Course

Live coding activity:

1. Open RStudio, and open a new text file. 
2. Save the file, and call it `md_explorer.md`
3. Add content to the document, using some markdown syntax such as:
    - Headers
    - Bold, Italics
    - Code font
    - Hyperlinks
4. Click `Preview` to convert the md file to HTML. Try pdf, too!
    - Which to use? In general: printing to the page, pdf. Viewing on the screen, HTML.

Notable "flavours"/extensions to the basic markdown:

- GitHub-flavoured Markdown (Assignment 1)
- R Markdown (A future lesson)

Resources:

- [Original Markdown syntax](https://daringfireball.net/projects/markdown/syntax).
- [Cheatsheet](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) for md and gh-flavoured md. 

# Version Control with GitHub

## Learning Objectives: Version Control with GitHub

The concepts we'll be looking at are:

- Commits
- Diffs
- Commit History
- Branches
- Merging
- Merge Conflicts

Specifically, by the end of today's class, students are expected to be able to:

- Describe the difference between git and GitHub, and name similar software
- Edit plain text files on different branches on GitHub
- Navigate the commit history of various repository branches on GitHub
- Visualize a tree diagram of commits across branches
- Merge repository branches via pull requests on GitHub, resolving merge conflicts if necessary

## About Version Control

What is version control?

Why bother with version control?

- Don't fret removing stuff
- Leave a breadcrumb trail for troubleshooting
- "Undo" to a previous state
- Helps you define your work
- ...

What software is associated with version control?

- git, subversion, GitHub, GitLab, Bitbucket, ...

## Live-Coding: Making a new repo

To demonstrate version control concepts, we'll create a new GitHub repository, which will showcase our markdown exploration. 


1. Create a new repository called `stat545_md_explorer`.
    - Counts towards participation, so please keep this repo until the course is complete.
2. Say YES to initializing with a README.
3. Edit the README with something descriptive, like:
    - > This repo is part of a STAT 545 exercise to explore GitHub and markdown.
4. _Commit_ the changes, adding a _commit message_.
5. Drag and drop the `.md`, `.html`, and `.pdf` files that you made earlier in class onto the main repo page.
6. Explore the files in your repo. What's viewable? What's not?
    - Food for thought: Jenny Bryan on repo browsability: [happygitwithr repo-browsability](http://happygitwithr.com/repo-browsability.html).

You should now have a repo called `stat545_md_explorer` with a README file, and your `.md`, `.pdf`, and `.html` files from before. 

## Commits

Commits, diffs, and commit history.

## Live-Coding: Branching and Merging

The notion of _branching_ and _merging_ shows up seemingly everywhere in version control. You'll encounter _merge conflicts_, too.

To demonstrate concepts, let's look at a _repository branch_. There are other types of branches, as we'll see.

NOTE: I'm deferring the motivation for repo branching until later. 

1. Create a new branch via the home page of your repo (find the "branch" button). Call it `test1`.
2. To the README on the `test1` branch, add a relative link to the other `.md` file in the repo (using markdown syntax).
3. Explore: 
    - switch between branches to see that the repo structure is different.
    - Diagram of commit history for both branches.
4. Merge the branch to "master".

Part 2: 

1. Make a new branch called `test2`.
2. Edit line 1 of the README _on both branches_ to something different in both cases.
3. Try merging. You'll get a _merge conflict_ -- go ahead and resolve it, then merge. 

# Collaboration with GitHub

## Learning Objectives: Collaboration with GitHub

The primary focus here is learning about __leveraging GitHub's version control for collaboration__. The concepts are:

- Collaborators
- Forking
- Pull Request
- Release
- GitHub Pages

Specifically, by the end of today's class, students are expected to be able to:

- Make a basic website out of their GitHub repository using GitHub Pages
- Tag a release of their GitHub repository 

## Collaboration Concepts and Workflows

Let's look at the how and why of the following:

- Adding a collaborator
- Repo branching: why?
    - try new features
    - work separately
    - hold different content
- Private vs public repositories
    - Viewing is different from collaborating!
    - If you can, making your work public is a remarkably good thing: world of "open source".
- Forking as another type of branching
- Tag a release of your repo
- Turn your repo into a website using GitHub pages

# If we finish early

## csv files

- Their use for tabular data
- Their structure
- Editing them by hand

## More Markdown

Let's learn more about markdown, with a think-pair-share activity.

1. Form groups of size `n` (determined in-class)
2. "Think"-iteration: Each person is responsible for learning about a different type of markdown formatting, for 3 minutes:
    - Inserting images
    - Lists
    - Blockquotes
    - Code blocks
3. "Pair"-iteration: For max 1 minute per person, each person either:
    - teaches the other group members how to use the formatting they learned, OR
    - if you're lost, ask your group members for help on the basics. 
        - Don't feel bad! This happens and is normal, and is also useful for your team members. 
4. "Share"-iteration: Volunteer to share something that you learned!