---
title: "STAT 545 Class Meeting 03"
output:
    html_notebook:
        toc: true
        theme: cerulean
        number_sections: true
editor_options: 
  chunk_output_type: inline
---

Announcements:

- Participation grades from in-class activities are not based on _correctness_, but rather whether the activity was _attempted_. 
- Homework how-to (fork if you want to work privately); survey! We are not looking at your commit history for this one. 
- How to ask for help from TA's specifically!

Today's topics are:

- Getting familiar with R
- Intro to RMarkdown

To participate in today's lecture, you should have:

- R and RStudio installed
- Optionally, LaTeX installed for outputting to pdf.

# Getting Familiar with R

## Learning Objectives

By the end of today's class, students are expected to be able to:

- Have a sense of the capabilities, and pros and cons, of R
- Identify and probe the most prominent data types and data structures in R, with a special focus on data frames
- Demonstrate the concept of vectorization in R via simple computations
- Access the documentation of R functions
- Access functions/objects stored in external R packages
- Know about useful resources online to get help with R, and technical tools in general.
- Design effective questions through minimum workable examples (MWE's).

## Resources:

We'll be roughly following these resources:

- The [stat545.com: hello r](http://stat545.com/block002_hello-r-workspace-wd-project.html) page for exploring R objects.
- The [stat545.com: care-feeding-data](http://stat545.com/block006_care-feeding-data.html) page for exploring data frames.

More comprehensive resource:

- [adv-r: data structures](http://adv-r.had.co.nz/Data-structures.html) is a more comprehensive version of exploring R objects.
    - For those already experience with R: I recommend you look this over. You'll probably learn something new.   
    - Also applicable for those new to R, who want the depth.

Want to practice programming in R? Check out [R Swirl](https://swirlstats.com/) for interactive lessons. 

## R!

- R is not RStudio


# RMarkdown

## Learning Objectives

- Create an RMarkdown document and render it to md/html/pdf
- Style an RMarkdown document by editing the YAML header
- Demonstrate at least two RMarkdown code chunk options
- Informatively choose between writing an R script/RMarkdown/R Notebook.

## Resources

Here are some resources that are well-aligned with today's goals:

- The [stat545: Rmd test drive](http://stat545.com/block007_first-use-rmarkdown.html). Read this if you missed something from today's class.
- The [Rmd website](https://rmarkdown.rstudio.com/) has a fantastic walk-through [tutorial](https://rmarkdown.rstudio.com/lesson-1.html) that gives a great overview of RMarkdown. The following lessons parallel today's content:
    - Lessons 1-4 (Intro - Inline Code)
    - Lessons 9-10 (Output Formats - Notebooks)

Although not a learning resource, you might find the official [Rmd cheatsheet](http://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf) a useful reference.

To dig deeper into any (?) aspect of RMarkdown, check out the free [RMarkdown book](https://bookdown.org/yihui/rmarkdown/).

## Getting Started

You'll need to install RMarkdown. To do so, in any R console, run the following:

```
install.packages('rmarkdown')
```

## Old Content

- Care and feeding of data frames!
    - In our first R Markdown document, we will explore the Gapminder data.
    - [Basic care and feeding of data in R](block006_care-feeding-data.html)

RMarkdown:

- Differences between markdown and R markdown.
    - Includes LaTeX (super useful for theses -- check out LyX if you're new).
    - code chunks!
    - YAML header. Can make some [pretty html files](http://rmarkdown.rstudio.com/html_document_format.html) with YAML.
- How to render: `rmarkdown::render` or click "knit". 
    - Files: `Rmd` -> `md` -> `html` or `pdf` or word (and other permutations... `keep_md: yes` to keep the intermediate `md` file. Or `output: github_document`). [Useful slide](https://speakerdeck.com/jennybc/happy-git-and-github-for-the-user?slide=56)

# To do before next class

To participate in tomorrow's lecture, you should:

- Complete the course survey, if you haven't already.
    - You MUST do this in order to do your first assignment!
- LaTeX installed?

    