---
title: "STAT 545 Class Meeting 09: Tidy Data"
output:
    html_notebook:
        toc: true
        theme: cerulean
        number_sections: true
editor_options: 
  chunk_output_type: inline
---

## Review, and Looking Ahead

For the past two weeks, we've been looking at "clean" exploratory data analysis by:

- Wrangling single data frames with `dplyr`
- Making plots of that data with `ggplot2`

This is a powerful framework for drawing information from data. 

This week, we'll focus on data not in an immediately ready-to-use format:

- Today: data reshaping
- Thursday: joining two tables (Rashedul to take the lead)

Starting next week, the rest of the course will look at more advanced versions of what we've seen:

- R programming
- Factors
- Plotting (including `plotly`).

We'll finish with a discussion on the model-fitting paradigm in R, and the `broom` package.  


## Today's Lessons

Today's lessons are:

- `readr`: Reading and writing data into and out of R
- `tidyr`: Tidying and untidying data
- Time permitting: other `tidyr` goodies

## Resources

Concepts from today's class are closely mirrored by Jenny Bryan's [LOTR tidy data lesson](https://github.com/jennybc/lotr-tidy#readme).

## Participation

To get participation points for today, fill out the cm009-exercise.Rmd file with the class (get it from [Rmd](https://github.com/STAT545-UBC/Classroom/blob/master/notes/cm009-exercise.Rmd), or [from html](http://stat545.com/Classroom/notes/cm009-exercise.html)), and add it to your participation repo.

# Reading and Writing data

## Working Directory 

R has a notion of "working directory". You can get with `getwd()`, set (with caution) with `setwd()`.

## The functions

Let's see an example of how tabular data are stored:

- csv example: [gapminder](https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/gapminder.csv)
- tsv example: [LOTR](https://raw.githubusercontent.com/jennybc/lotr/master/lotr_clean.tsv)

Reading and writing csv's

| Tool | Reading | Writing |
|------|---------|---------|
| Base R | `read.csv()` | `write.csv()` |
| tidyverse (`readr`) | `read_csv()` | `write_csv()` |

Reading and writing tsv's

| Tool | Reading | Writing |
|------|---------|---------|
| Base R | `read.delim()` | `write.table(sep="\t")` |
| tidyverse (`readr`) | `read_tsv()` | `write_tsv()` |


Reading and writing delimited files in general

| Tool | Reading | Writing |
|------|---------|---------|
| Base R | `read.delim()` | `write.table()` |
| tidyverse (`readr`) | `read_delim()` | `write_delim()` |

With Base R: beware the factors with `read.csv()`!

## Making tibbles within R

Base R: `data.frame()` function.

Tidyverse version: `tibble()` function from `tibble` package.

Truly manual construction of tibbles: `tribble()` from the `tibble` package. 

# Tidy Data

## Learning Objectives

Here are the concepts we'll be exploring in this lesson:

- tidy data
- gather
- spread

By the end of this lesson, students are expected to be able to:

- identify when data are tidy, and when they are not.
- when either form is useful.
- use the `tidy::gather()` and `tidyr::spread()` functions to convert between tidy and untidy data

## Tidy Data

We'll look at Jenny's [intro](https://github.com/jennybc/lotr-tidy/blob/master/01-intro.md) page for an example of tidy/untidy data. 

## gather and spread

History: Data reshaping has not been the most natural thing to program. First came the `reshape` package. Then the `reshape2` package. Now the `tidyr` package makes it easy(er).

Spreadsheets like Excel? pivot. 

Let's try some exercises. 