---
title: "STAT 545 Class Meeting 01: Intro to Data Analytic Work"
output:
    html_notebook:
        toc: true
        theme: cerulean
        number_sections: true
editor_options: 
  chunk_output_type: inline
---

# Today's Outline

By the end of today's class, students are expected to be able to:

- List 4 ways to get help in this course
- Create and comment on GitHub Issues
- Write markdown to produce simple documents as GitHub Issues.

# Activities

## GitHub activity

[5 minute timer](https://www.youtube.com/watch?v=MxQWLbdGLfE).

1. Register for a free account on github.com. You'll be using this account for the duration of the course.
    - Want detailed instructions? See [happygitwithr: Section 5](http://happygitwithr.com/github-acct.html)
2. Complete [this survey](https://forms.gle/VWYLQpyt7eNXdvZu6).
3. Navigate to the [Announcements](https://github.com/STAT545-UBC-hw-2019-20/Announcements) repository.
4. Click `Watch` on the upper-right corner of the repo
    - This is so that you get email notifications whenever an announcement is posted (under the "Issues" tab).
5. Go to the Issues section of the repository, and comment on the Issue I created called "Introduce yourself!". In the comment, say who you are, and greet the person above you -- be sure to tag them by their username using `@username`. 
6. Please put up a profile photo -- it makes the STAT 545 community more personable. You can do this from your profile homepage. 
7. OPTIONAL: Register for the [Student Developer Pack](https://education.github.com/pack) with GitHub for a bunch of free perks for students!

# Quiz

(to make??)

- Rank? What are four ways to ask for help in this course? In real life?
- What is a github repository? Org? Issue?


# To do before next time

- Please fill out [this survey](https://goo.gl/forms/UPvRA6a9WRod8JPb2), so that we can match you to your GitHub account.
- Install the software stack -- go to office hours if you are having trouble.
- Remember to bring your laptop to every class, as we will have live-coding activities. 



